### ISSUE TITLE
/room url 3개로 세분화 필요

### ISSUE THREAD

**Issue by dasd412** [SWM14-Architect/moview-frontend#29]
구글 analytics에서 /room url이 입력, 채팅, 평가 전부 통합되어 있기 때문에 구분하기가 힘듬.
해당 url  바꿀 필요가 있음.

**Comment by saebyeok0306** [comment]
https://velog.io/@tw4504/React-GA%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%9C-react%EC%99%80-google-analytics-%EC%97%B0%EB%8F%99%ED%95%98%EA%B8%B0

page view 정보를 구글 analytics에 건내줄 때 urlpath가 /room일 경우, 입력페이지인지 채팅페이지인지 결과페이지인지에 대한 정보도 함께 포함시켜서 전송시키는 방식으로 해결이 가능할 듯 합니다.
