### ISSUE TITLE
cloudfront 배포 이후 jwt 및 쿠키 문제

### ISSUE THREAD

**Issue by dasd412** [SWM14-Architect/moview-frontend#49]
cloudfront에 실제 배포 후 문제가 발생한다.

1. JWT 토큰이 발급되더라도 새로 고침하면 쿠키가 사라진다.
2. login callback url에서 404 에러가 발생한다.

**Comment by dasd412** [comment]
![스크린샷 2023-10-11 오후 8 59 52](https://github.com/SWM14-Architect/moview-frontend/assets/45190017/07cd3d91-13a4-4224-a8ea-d0c64f49c3cc)

쿠키쪽 건드려봐야 할 듯

**Comment by dasd412** [comment]
https://seob.dev/posts/%EB%B8%8C%EB%9D%BC%EC%9A%B0%EC%A0%80-%EC%BF%A0%ED%82%A4%EC%99%80-SameSite-%EC%86%8D%EC%84%B1/

**Comment by dasd412** [comment]
https://be-student.tistory.com/72

**Comment by dasd412** [comment]
다음 사진에서 aws 내에서 제공하는 에러 메시지를 조사할 필요가 있다.

![스크린샷 2023-10-11 오후 9 34 17](https://github.com/SWM14-Architect/moview-frontend/assets/45190017/fee8bc73-28bd-4c6a-a230-2de9ac0d2e0a)

**Comment by dasd412** [comment]
검색어 cloudfront jwt cookie disappear

참고 링크
https://stackoverflow.com/questions/59870947/cloudfront-seems-to-lose-my-json-web-token-on-refresh

https://stackoverflow.com/questions/47366993/missing-authentication-token-error-with-cloudfront-api-gateway

**Comment by dasd412** [comment]
https://velog.io/@xogml951/CloudfrontS3-Frontend-%EB%B0%B0%ED%8F%AC

**Comment by dasd412** [comment]
<원인 1 : 쿠키 도메인이 다르다>

[클라우드 프론트]
새로 고침 시 쿠키가 제거된다. 쿠키 도메인이 moview.io인 경우 남으며, api.moview.io인 경우는 제거된다. (전자는 s3 도메인 주소, 후자는 ec2 도메인 주소다. s3 도메인 주소인 거는 Google Analytics 쿠키 뿐.) 

[로컬]
모든 jwt 관련 쿠키와 Google Analytics 쿠키가 도메인이 같다. 전부 localhost임.

**Comment by dasd412** [comment]
<원인 2 : X-CSRF-TOKEN을 찾을 수 없다. >

다음은 flask-jwt의 jwt_decorator 의 일부 코드이다. 디버그 한 결과는 //으로 작성했다.

```
if token_type == "access":
    cookie_key = config.access_cookie_name // cookie_key == accss_token_cookie
    csrf_header_key = config.access_csrf_header_name //csrf_header_key == X-CSRF-TOKEN
    csrf_field_key = config.access_csrf_field_name //csrf_field_key ==  csrf-token

encoded_token = request.cookies.get(cookie_key)

if not encoded_token:
    raise NoAuthorizationError('Missing cookie "{}"'.format(cookie_key))

if config.csrf_protect and request.method in config.csrf_request_methods:
    csrf_value = request.headers.get(csrf_header_key, None) //csrf_value는 프론트 csrf_access_token 값과 같음
    if not csrf_value and config.csrf_check_form:
        csrf_value = request.form.get(csrf_field_key, None)
    if not csrf_value:
        raise CSRFError("Missing CSRF token")
else:
    csrf_value = None

return encoded_token, csrf_value
```

위 코드에서
`request.headers.get(csrf_header_key, None)` 의 경우 csrf_header_key를 찾을 수 없으면 None으로 리턴한다.

즉 클라우드프론트 -> EC2로 갈 때 X-CSRF-TOKEN을 찾을 수 없다는 뜻이다.

로컬에서도 api 호출할 때 csrf_access_token 쿠키를 제거하고 호출했더니, 클라우드 프론트랑 동일하게 401 error를 발생시켰다.

**Comment by dasd412** [comment]
현재 클라우드 프론트에서 api 호출할 경우, 백엔드는 다음 에러를 뱉는다.
```
{
    "message": "The method is not allowed for the requested URL."
}
```

그리고 다음 절차를 밟고 강제 로그아웃 당한다.
1. light 과 같은 api 호출 후 401 에러 발생 
2. refresh가 바로 연달아 호출 이후 401 에러 발생

2.가 발생하는 원인은 api_instance.js의 useEffect() 부분을 참고하면 알 수 있다.
api 호출 후 실패하면 바로 refresh를 호출하기 때문.

**Comment by dasd412** [comment]
https://www.inflearn.com/questions/342672/express-aws-%EB%B0%B0%ED%8F%AC-%ED%9B%84-%EC%84%B8%EC%85%98-%EC%BF%A0%ED%82%A4

**Comment by dasd412** [comment]
[Cross-Domain Cookies 로 검색할 시]
우리랑 거의 비슷한 문제가 발생함.

https://velog.io/@code-bebop/CORS%EC%9D%98-Cookie

https://velog.io/@ooooorobo/%EB%8B%A4%EB%A5%B8-%EB%8F%84%EB%A9%94%EC%9D%B8%EC%97%90-%EC%BF%A0%ED%82%A4-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0

https://blossoming-man.tistory.com/entry/https%EC%99%80-cross-domain%EC%97%90%EC%84%9C-%EC%84%9C%EB%B2%84%EC%99%80-%ED%86%B5%EC%8B%A0-%EC%8B%9C-%EC%BF%A0%ED%82%A4-%EB%B0%9B%EB%8A%94-%EB%B2%95

**Comment by dasd412** [comment]
[CSRF double submit tokens]

CSRF (Cross-Site Request Forgery)는 공격자가 사용자의 세션을 악용하여 사용자의 의지와는 별개로 웹 애플리케이션에 변조된 요청을 보내는 보안 취약점입니다. CSRF를 방어하기 위한 대표적인 방법 중 하나가 "double submit tokens" 방식입니다.

CSRF Double Submit Tokens의 기본 아이디어는 다음과 같습니다:

**1. 사용자가 웹사이트에 로그인하면 서버는 CSRF 토큰을 생성합니다.
2. 이 토큰은 클라이언트 측의 쿠키에 저장됩니다. 동시에 이 토큰 값은 폼의 숨겨진 필드나 AJAX 요청의 헤더 등으로도 웹 페이지에 포함됩니다.
3.사용자가 액션(예: 폼 제출)을 수행하려 할 때, 요청과 함께 이 토큰 값이 서버로 전송됩니다. 이 때, 쿠키의 토큰 값과 폼에서 전송된 토큰 값 두 가지를 모두 검증합니다.
4.만약 두 토큰 값이 일치하지 않으면, 요청은 CSRF 공격으로 간주하고 거부됩니다.**

이 방식의 장점은 상태를 저장할 필요가 없다는 것입니다. 즉, 서버는 각각의 사용자에 대해 토큰 값을 별도로 저장하거나 추적할 필요가 없습니다. 클라이언트가 제출한 두 토큰 값만 비교하면 됩니다.

하지만 이 방식도 완벽하지는 않습니다. 만약 공격자가 XSS (Cross-Site Scripting) 공격을 성공적으로 수행하게 되면, 공격자는 이 토큰 값을 가져와 CSRF 공격을 수행할 수 있습니다. 따라서, CSRF 방어와 함께 XSS 취약점도 잘 관리하는 것이 중요합니다.

**Comment by saebyeok0306** [comment]
CloudFront에서 Header 정책은 사실 큰 의미가 없었음.
쿠키의 도메인이 달라서, 프론트쪽에서 쿠키를 얻어오질 못해서 null인 값을 x-csrf-token header에 실었기 때문에 누락된 걸로 확인되었다.

아래 사진은 크로스 도메인 쿠키 문제를 해결 한 후, 정책을 기본값으로 바꿨을 때도 Header가 잘 넘어가는지 테스트해봄.
그 결과 여전히 Header에 잘 담겨있음.

![image](https://github.com/SWM14-Architect/moview-frontend/assets/67100702/117d09a0-93c0-4eed-8ff7-7e65aa1ed537)
![image](https://github.com/SWM14-Architect/moview-frontend/assets/67100702/89839349-bce2-42e5-be0f-ff7bd4cfbd78)

**Comment by dasd412** [comment]
[현재 기준]
백엔드 쪽만 SameSite = None 부여하고, 쿠키 도메인을 "moview.io"로 설정함.

그 결과 csrf double submit dose not match 에러가 발생함.





[3:21](https://w1682137080-hpr976928.slack.com/archives/C054ADPP2HG/p1697091683613879)
쿠키도메인을 '.[moview.io](http://moview.io/)'으로 설정한 거

**Comment by dasd412** [comment]
아래 그림 처럼 쿠키를 moview.io만 남기고 api.moview.io 쿠키는 삭제 하길 바람.
api.moview.io 쿠키는 클라우드 프론트가 캐싱한 거 때문에 남아있는 거 같음. 

![스크린샷 2023-10-12 오후 3 30 15](https://github.com/SWM14-Architect/moview-frontend/assets/45190017/2dcec07f-bbb3-4843-aa1f-d39555cde6e9)

**Comment by saebyeok0306** [comment]
![image](https://github.com/SWM14-Architect/moview-frontend/assets/67100702/d98dfc43-03b3-4c41-9884-ced178e2ff70)

배포 후 발생한 쿠키 문제는 위의 2개 옵션으로 해결됨.
개발버전과 배포버전을 분리해서 관리해야하는 옵션.
