### ISSUE TITLE
토큰 사용량 제한 Error 메시지 catch 필요

### ISSUE THREAD

**Issue by dasd412** [SWM14-Architect/moview-frontend#54]
이 것 까지만 하고 메인 브랜치 머지 후, QA 진행.
그리고 바로 커뮤니티에 홍보.

**Comment by dasd412** [comment]
https://platform.openai.com/docs/guides/rate-limits/overview

**Comment by dasd412** [comment]
[백엔드에서 할 일]
1. 에러 캐치 로직 추가
2. **에러 발생 시 로깅 추가**

[프론트에서 할 일]
1. 자소서 개수 5개에서 2개로 제한 (입력 페이지)
2. 사용 방법에서 자소서 개수 5개에서 2개로 설명 변경
3. 백엔드에서 에러 캐치한 거 받을 시, toast로 메시지 출력

**Comment by ssfic3380** [comment]
자소서는 대부분 3개가 많아서 최소 3개는 해야할듯합니다.

**Comment by dasd412** [comment]
`Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 1.0 seconds as it raised RateLimitError: Rate limit reached for gpt-3.5-turbo in organization ~~ on tokens per min. Limit: 90000 / min. Current: 89866 / min. Contact us through our help center at help.openai.com if you continue to have issues..`

![스크린샷 2023-10-15 오후 12 17 06](https://github.com/SWM14-Architect/moview-frontend/assets/45190017/bee46c0e-ca62-44d1-bf51-d57a72ed7aff)

**Comment by dasd412** [comment]
조사해본 결과, Openai 그대로 쓰는 거는 
```
try:

except openai.RateLimitError as e:
```
 
로 하면 될 것 같은데, langchain은 해당 에러를 wrapping하고 있음.
그리고 위 터미널 결과처럼 print()를 해주고 있다. 위 사진의 코드 어디에 try ~ except를 해도 예외가 잡히지 않고 있다.

문제는 langchain 어디에서 error catch를 하는 객체를 만들어줘야 할지, 그리고 무슨 메서드를 만들어줘야 할 지 모르겠다는 것이다.
(langchain의 쓸데없는 복잡함과 어지러운 문서 때문)

[결론]
1. 현재 langchain에서 예외 캐치를 하는 것은 포기가 나아보인다.
2. 미들웨어 또는 프론트엔드에서 최대한 제한한다.
3. 최종적으론 langchain 버리고 openai를 쓴다.
